KTS/Models/Services.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
namespace KTS.Models
{
    public class Services
    {
        [Key]
        public string Serviceid { get; set; }

        [Display(Name ="Price")]
        public decimal price { get; set; }

        public string productTy { get; set; }
        public ProductType GetProductType { get; set; }



    }
}

KTS/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KTS.Models;
using KTS.data;

namespace KTS.Controllers
{
    public class BrandsController : Controller
    {
        private ktsContext db = new ktsContext();

        // GET: Brands
        public ActionResult Index()
        {
            var pBrands = db.PBrands.Include(b => b.type);
            return View(pBrands.ToList());
        }

        // GET: Brands/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brands brands = db.PBrands.Find(id);
            if (brands == null)
            {
                return HttpNotFound();
            }
            return View(brands);
        }

        // GET: Brands/Create
        public ActionResult Create()
        {
            ViewBag.productTy = new SelectList(db.Ptype, "productTy", "productTy");
            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "brandID,brandName,productTy")] Brands brands)
        {
            if (ModelState.IsValid)
            {
                db.PBrands.Add(brands);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.productTy = new SelectList(db.Ptype, "productTy", "productTy", brands.productTy);
            return View(brands);
        }

        // GET: Brands/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brands brands = db.PBrands.Find(id);
            if (brands == null)
            {
                return HttpNotFound();
            }
            ViewBag.productTy = new SelectList(db.Ptype, "productTy", "productTy", brands.productTy);
            return View(brands);
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "brandID,brandName,productTy")] Brands brands)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brands).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.productTy = new SelectList(db.Ptype, "productTy", "productTy", brands.productTy);
            return View(brands);
        }

        // GET: Brands/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brands brands = db.PBrands.Find(id);
            if (brands == null)
            {
                return HttpNotFound();
            }
            return View(brands);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Brands brands = db.PBrands.Find(id);
            db.PBrands.Remove(brands);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KTS/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KTS.Models;
using KTS.data;

namespace KTS.Controllers
{
    public class EmployeesController : Controller
    {
        private ktsContext db = new ktsContext();

        // GET: Employees
        public ActionResult Index()
        {
            return View(db.emps.ToList());
        }

        // GET: Employees/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.emps.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmpNo,EName,EmployeeId,EsName,Eaddress,Ecell,FascimleContact,taxNo")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.emps.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.emps.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmpNo,EName,EmployeeId,EsName,Eaddress,Ecell,FascimleContact,taxNo")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.emps.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Employee employee = db.emps.Find(id);
            db.emps.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KTS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KTS.Models;
using KTS.data;

namespace KTS.Controllers
{
    public class HomeController : Controller
    {
        private ktsContext db = new ktsContext();

        public ActionResult Index()
        {
            
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult ProductsRe(string s)
        {
            if (s != null)
            {
                var i = (from d in db.InventoryT.Include(p => p.GetProducts).Where(y => y.ProductModelName.StartsWith(s)) select d);
                return View(i);
            }
            var inventoryT = (from d in db.InventoryT.Include(i => i.GetProducts) select d);
            return View(inventoryT.ToList());



        }
        // GET: Products
        

        public ActionResult V()
        {
            // where is this one going?
            var search = db.services.Where(p => p.Serviceid == "Vulcanizing").ToList();

            return  View("Service",search);
        }

        public ActionResult B()
        {
            // where is this one going?
            var search = db.services.Where(p =>p.Serviceid== "Balancing&Fitting").ToList();

            return View("Service", search);
        }

        public ActionResult W()
        {
            // where is this one going?
            var search = db.services.Where(p => p.Serviceid == "Wheel Alignment").ToList();

            return View("Service", search);
        }

        public ActionResult Tyres(string s)
        {
            if (s != null)
            {
                var t = db.InventoryT.Include(p => p.GetProducts).Where(p => p.GetProducts.GetBrands.productTy.StartsWith(s)).ToList();

                return View("ProductsRe", t);
            }
            
            var tyre = db.InventoryT.Include(p => p.GetProducts).Where(p => p.GetProducts.GetBrands.productTy == "Tyres").ToList();

            return View("ProductsRe", tyre);

        }





        public ActionResult Rims(string s)
        {
            if (s != null)
            {
                var e = db.InventoryT.Include(i => i.GetProducts).Where(p => p.GetProducts.GetBrands.productTy.StartsWith(s)).ToList();
                return View("ProductsRe", e);
            }
            
               

           

                var r = db.InventoryT.Include(i => i.GetProducts).Where(p => p.GetProducts.GetBrands.productTy == "Rims").ToList();
              return View("ProductsRe", r);

        }

        public ActionResult Lugs(string s)
        {

            if (s != null)
            {
                var L= db.InventoryT.Include(i => i.GetProducts).Where(p => p.GetProducts.GetBrands.productTy.StartsWith(s)).ToList();

                return View("ProductsRe", L);
            }


            var Lug = db.InventoryT.Include(i => i.GetProducts).Where(p => p.GetProducts.GetBrands.productTy == "Accessories").ToList();

            return View("ProductsRe", Lug);

        }


        public ActionResult Employee()
        {

            return View("Employee");
        }

    }
      
}

KTS/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KTS.Models;
using KTS.data;

namespace KTS.Controllers
{
    public class ServicesController : Controller
    {
        private ktsContext db = new ktsContext();

        // GET: Services
        public ActionResult Index()
        {
            return View(db.services.ToList());
        }

        // GET: Services/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Services services = db.services.Find(id);
            if (services == null)
            {
                return HttpNotFound();
            }
            return View(services);
        }

        // GET: Services/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Serviceid,price,serviceImage")] Services services, HttpPostedFileBase image1)
        {
            if (ModelState.IsValid)
            {
              

                db.services.Add(services);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(services);
        }

        // GET: Services/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Services services = db.services.Find(id);
            if (services == null)
            {
                return HttpNotFound();
            }
            return View(services);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Serviceid,price")] Services services)
        {
            if (ModelState.IsValid)
            {
                db.Entry(services).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(services);
        }

        // GET: Services/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Services services = db.services.Find(id);
            if (services == null)
            {
                return HttpNotFound();
            }
            return View(services);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Services services = db.services.Find(id);
            db.services.Remove(services);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KTS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>All Policies are here</h2>

<h2>No Accounts will be iven without a credit history being done</h2>
<h2>no tyres repaired will be given without payment</h2>
<h2>No no breakdowns will be done without finding out exactly where the vehicle is and half pament made</h2>


<p></p>

KTS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<body>
    <div class="container body-content">
        <h1>Contact Us</h1>
        <div>
            <h3><span class="glyphicon glyphicon-phone"></span> Call Us</h3>
            <address>
                <abbr title="Phone">Sagren : </abbr>
                +2784 264 4028
            </address>

            <h3><span class="glyphicon glyphicon-envelope"></span> Email Us</h3>
            <address>
                <strong>Email : </strong> <a href="mailto:Marketing@example.com">ktspinetown@gmail.com</a>
            </address>
        </div>


        <div>
            <h3><span class="glyphicon glyphicon-map-marker"></span> Find Us Here</h3>
            <p>
                16 Gillets (Gate 3)<br />
                Ashley,Pinetown
            </p>
            <div style="border-radius:25px">
                <iframe style="border-radius:25px" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13846.270014225148!2d30.85070897350217!3d-29.81903686267986!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1ef6fe60168c6537%3A0x7754c89d9818ab8b!2s16%20Gillitts%20Rd%2C%20New%20Germany%2C%20Pinetown%2C%203620!5e0!3m2!1sen!2sza!4v1567183131894!5m2!1sen!2sza" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
            </div>
        </div>

    </div>

</body>

KTS/Views/Home/Employee.cshtml
@{
    ViewBag.Title = "Admin";
}
<head>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>
<body >
    <div class="container body-content">

        <div class="align-content-center">
            <h2>Administrator and Employee Use</h2>
            <i class='fas fa-lightbulb' style='font-size:24px;color:yellow'></i>
            @Html.ActionLink("Create a new Product Type", "Create", "ProductTypes")

            <br />
            <br />

            <i class='fas fa-file-alt' style='font-size:24px;color:green'></i>
            @Html.ActionLink("Add A new Brand ", "Create", "Brands")


            <br />
            <br />

            <i class='fas fa-file-alt' style='font-size:24px;color:green'></i>
            @Html.ActionLink("Add A new Supplier ", "Create", "Suppliers")
            <br />
            <br />

            <i class='fas fa-tag' style='font-size:24px;color:red'></i>
            @Html.ActionLink("Create a Procduct ", "Create", "Products")
            <br />


            <br />

            <i class='fas fa-tag' style='font-size:24px;color:red'></i>
            @Html.ActionLink("Add products to Inventory ", "Create", "Inventories")

            <br />


            <br />

            <i class='fas fa-tag' style='font-size:24px;color:red'></i>
            @Html.ActionLink("Add Service ", "Create", "Services")

            <br /><br />

            <i class='fas fa-tag' style='font-size:24px;color:red'></i>
            @Html.ActionLink("Bookings", "Index", "Bookings")


        </div>
    </div>

</body> 

KTS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "KTS Tyres";
}



<body>


    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                @*<img src="ny.jpg" alt="Tyres" width="1200" height="700">*@
                @*<img src="~/Content/pics/Rims.jpg" style="width:100%;height:500px;" />*@
                <img src="~/Content/pics/Rims.jpg" class="img-responsive" style="width:100%" />

                <div class="carousel-caption">
                    <h3>Tyres</h3>
                    <p>Pick and choose from our extensive collection of quality tyres.</p>
                </div>
            </div>

            <div class="item">
                @*<img src="chicago.jpg" alt="Services" width="1200" height="700">*@
                @*<img src="~/Content/pics/automobile-number-odometer-248747.jpg" style="width:100%;height:500px;" />*@
                <img src="~/Content/pics/auto-automobile-automotive-919073.jpg" class="img-responsive" style="width:100%" />

                <div class="carousel-caption">
                    <h3>Services</h3>
                    <p>We offer a range of motor vehicular services to fit your needs</p>
                </div>
            </div>

            <div class="item">
                @*<img src="la.jpg" alt="Rims" width="1200" height="700">*@
                <img src="~/Content/pics/car-pic - carousel.jpg" class="img-responsive" style="width:100%" />
                <div class="carousel-caption">
                    <h3>Rims</h3>
                    <p>Even though traffic is a mess, we'll make sure you look stunning in it with our choice selection of rims.</p>
                </div>
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <!-- Container (The Main Section) -->
    <div class="container text-center">
        <h3>KTS Tyres</h3>
        <p><em>Service With A Smile</em></p>
        <p class="col-md-3"></p>
        <p class="col-md-6">
            Welcome to <em>KwaZulu Tyre Services</em>. We are a leading provider of quality tyres
            and a multitude of motor vehilcular services such
            wheel alignment and vulcanizing.
        </p>
        <p class="col-md-3"></p>
        <br /><br />

        <div class="row text-center">
            <a href="http://localhost:9152/Home/Tyres">
                <div class="col-sm-4">
                    <div class="thumbnail" style="background-color:#2d2d30;">
                        <img src="~/Content/pics/tyre2.jpg" alt="Paris" style="border-top-right-radius:25px;border-top-left-radius:25px;width:100%;" />
                        <p style="color:white;"><strong>Tyres</strong></p>
                    </div>
                </div>
            </a>
            <a href="http://localhost:9152/Home/Rims">
                <div class="col-sm-4">
                    <div class="thumbnail" style="background-color:#2d2d30;">
                        <img src="~/Content/pics/BBSRim.jpg" alt="Rims" style="border-top-right-radius:25px;border-top-left-radius:25px;" />
                        <p style="color:white;"><strong>Rims</strong></p>
                    </div>
                </div>
            </a>
            <a href="http://localhost:9152/Home/Lugs">
                <div class="col-sm-4">
                    <div class="thumbnail" style="background-color:#2d2d30;">
                        <img src="~/Content/pics/Benz.jpg" alt="Accessories" style="border-top-right-radius:25px;border-top-left-radius:25px;" />
                        <p style="color:white;"><strong>Accessories</strong></p>
                    </div>
                </div>
            </a>
        </div>

        <div class="row text-center">
            <a href="http://localhost:9152/Home/V">
                <div class="col-sm-4">
                    <div class="thumbnail" style="background-color:#2d2d30;">
                        <img src="~/Content/pics/BlackRim.jpg" alt="Vulcanizing" style="border-top-right-radius:25px;border-top-left-radius:25px;" />
                        <p style="color:white;"><strong>Vulcanizing</strong></p>
                    </div>
                </div>
            </a>
            <a href="http://localhost:9152/Home/W">
                <div class="col-sm-4">
                    <div class="thumbnail" style="background-color:#2d2d30;">
                        <img src="~/Content/pics/wheel1.jpg" alt="Wheel Alignment" style="border-top-right-radius:25px;border-top-left-radius:25px;" />
                        <p style="color:white;"><strong>Wheel Alignment</strong></p>
                    </div>
                </div>
            </a>
            <a href="http://localhost:9152/Home/B">
                <div class="col-sm-4">
                    <div class="thumbnail" style="background-color:#2d2d30;">
                        <img src="~/Content/pics/Tools.jpg" alt="Balancing & Fitting" style="border-top-right-radius:25px;border-top-left-radius:25px;" />
                        <p style="color:white;"><strong>Balancing & Fitting</strong></p>
                    </div>
                </div>
            </a>
        </div>

    </div>

    <!-- Container (Specials Section) -->
    <div class="bg-1">
        <div class="container">
            <h3 class="text-center">SPECIALS</h3>
            <p class="text-center">
                Have a browse of some of the specials we currently have on offer.<br>
                Hopefully you'll find just what you need at a reduced price.
            </p>
            <br />


            <div class="row text-center">
                <div class="col-sm-4">
                    <div class="thumbnail">
                        @*<img src="newyork.jpg" alt="New York" width="400" height="300">*@
                        <img src="~/Content/pics/civic.jpg" style="border-top-right-radius:25px;border-top-left-radius:25px;" />
                        <p><strong>Goodyear Tyres</strong></p>
                        <p>15% Off Select Goodyear Tyres</p>
                        <button class="btn" data-toggle="modal" data-target="#myModal">Buy</button>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="thumbnail">
                        @*<img src="paris.jpg" alt="Paris" width="400" height="300">*@
                        <img src="~/Content/pics/Rim1.jpg" style="border-top-right-radius:25px;border-top-left-radius:25px;" />
                        <p><strong>BBS Rims</strong></p>
                        <p>20% Off Selected BBS Rims</p>
                        <button class="btn" data-toggle="modal" data-target="#myModal">Buy</button>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="thumbnail">
                        @*<img src="sanfran.jpg" alt="San Francisco" width="400" height="300">*@
                        <img src="~/Content/pics/civicEk.jpg" style="border-top-right-radius:25px;border-top-left-radius:25px;" />
                        <p><strong>Wheel Alignment</strong></p>
                        <p>30% Off Wheel Alignment</p>
                        <button class="btn" data-toggle="modal" data-target="#myModal">Buy</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">×</button>
                        <h4><span class="glyphicon glyphicon-lock"></span> Special</h4>
                    </div>
                    <div class="modal-body">
                        <form role="form">
                            <div class="form-group">
                                <label for="psw"><span class="glyphicon glyphicon-shopping-cart"></span> Was : <del>R2000</del> | Now : R1600 per tyre</label>
                                <input type="number" class="form-control" id="psw" placeholder="How many?">
                            </div>

                            @*<div class="form-group">
                                    <label for="usrname"><span class="glyphicon glyphicon-user"></span> Send To</label>
                                    <input type="text" class="form-control" id="usrname" placeholder="Enter email">
                                </div>*@

                            <button type="submit" class="btn btn-block">
                                Add To Cart
                                <span class="glyphicon glyphicon-ok"></span>
                            </button>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal">
                            <span class="glyphicon glyphicon-remove"></span> Cancel
                        </button>
                        @*<p>Need <a href="#">help?</a></p>*@
                    </div>
                </div>
            </div>
        </div>
    </div>


    <img src="~/Content/pics/BMW.jpg" class="img-responsive" style="height:20%" />


    <script>
        $(document).ready(function () {
            // Initialize Tooltip
            $('[data-toggle="tooltip"]').tooltip();

            // Add smooth scrolling to all links in navbar + footer link
            $(".navbar a, footer a[href='#myPage']").on('click', function (event) {

                // Make sure this.hash has a value before overriding default behavior
                if (this.hash !== "") {

                    // Prevent default anchor click behavior
                    event.preventDefault();

                    // Store hash
                    var hash = this.hash;

                    // Using jQuery's animate() method to add smooth page scroll
                    // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
                    $('html, body').animate({
                        scrollTop: $(hash).offset().top
                    }, 900, function () {

                        // Add hash (#) to URL when done scrolling (default click behavior)
                        window.location.hash = hash;
                    });
                } // End if
            });
        })
    </script>

</body>

KTS/Views/Home/Service.cshtml
@model IEnumerable<KTS.Models.Services>

@{
    ViewBag.Title = "Service";
}

<h2>Service</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Serviceid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Serviceid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>

        </tr>
    }
    


</table>